# Generated by Django 3.0 on 2021-04-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='null', max_length=50)),
                ('author', models.CharField(default='null', max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('accesslevel', models.CharField(default=4, max_length=50)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('designation', models.IntegerField(default=1)),
                ('colourcode', models.AutoField(primary_key=True, serialize=False)),
                ('clientid', models.CharField(default='xyz', max_length=17)),
                ('cipher_text', models.CharField(default='xyz', max_length=25)),
                ('hash_text', models.CharField(default='xyz', max_length=65)),
            ],
        ),
    ]
