# Generated by Django 3.0 on 2021-04-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('leakdetetcetedat', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=100)),
                ('status', models.CharField(default='Not Viewed', max_length=20)),
            ],
        ),
    ]
