# Generated by Django 3.0 on 2021-04-30 00:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 0, 28, 25, 691209, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='history',
            name='leakdetetcetedat',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 0, 28, 25, 692205, tzinfo=utc)),
        ),
    ]
