# Generated by Django 3.0 on 2021-05-20 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210513_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='check/')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 12, 28, 57, 449640, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='history',
            name='leakdetetcetedat',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 12, 28, 57, 450703, tzinfo=utc)),
        ),
    ]
